// This file is generated by boneyard-js CLI
// It registers captured bone snapshots for skeleton resolution
import { registerBones } from 'boneyard-js/react';

// Initialize with empty registry
registerBones({});
